In [16]:
import numpy as np

def nump():
    a = np.random.random((5,4))
    print(a)
    print(a.shape)
    b = np.random.randint(1,2, size=(5,5))
    print(b)
    
    element = a[3,2]
    print(a[0,1:3])
    
if __name__=="__main__":
    nump()

[[0.61347198 0.6389329  0.79460096 0.22982892]
 [0.96418733 0.75427727 0.26292576 0.42356552]
 [0.04933434 0.79634862 0.27648781 0.33453505]
 [0.38574199 0.95565975 0.88164598 0.24707466]
 [0.41757089 0.26093345 0.5366673  0.20093999]]
(5, 4)
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[0.6389329  0.79460096]
